esphome:
  name: fontaine-chat
  friendly_name: fontaine-chat
  on_boot:
      priority: 600 
      then:
        - script.execute: gestion_cycle_pompe
        - if:
            condition:
              lambda: 'return id(mode_uv).current_option() == "Automatique";'
            then:
              - script.execute: cycle_uv_auto

bk72xx:
  board: cbu

logger:

api:
  reboot_timeout: 2min

ota:
  - platform: esphome
    version: 2

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"

time:
  - platform: sntp
    id: my_time
    timezone: "Europe/Paris"

globals:
  - id: temps_restant_pompe
    type: int
    initial_value: '0'
  - id: temps_restant_uv
    type: int
    initial_value: '0'
  
number:
  - platform: template
    name: "Jours avant changement de filtre"
    id: filtre_jours_restants
    min_value: 0
    max_value: 30
    initial_value: 30
    step: 1
    optimistic: true
    restore_value: true
    icon: "mdi:air-filter"
    entity_category: diagnostic

select:
  - platform: template
    name: "Mode de la Pompe"
    id: mode_pompe
    icon: "mdi:auto-fix"
    options:
      - "Arrêt"
      - "Continu"
      - "Intermittent (5m ON / 15m OFF)"
    initial_option: "Continu"
    optimistic: true
    restore_value: true
    on_value:
      then:
        - script.execute: gestion_cycle_pompe

  - platform: template
    name: "Mode Lampe UV"
    id: mode_uv
    icon: "mdi:auto-fix"
    options:
      - "Automatique"
      - "Manuel"
    initial_option: "Automatique"
    optimistic: true
    restore_value: true
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x == "Automatique";'
            then:
              - logger.log: "Mode UV : Automatique activé"
              - script.execute: cycle_uv_auto
            else:
              - logger.log: "Mode UV : Manuel activé"
              - script.stop: cycle_uv_auto
              - switch.turn_off: lampe_uv
          
button:
  - platform: template
    name: "Réinitialiser le filtre"
    id: reset_filtre_btn
    icon: "mdi:restart"
    on_press:
      then:
        - number.set:
            id: filtre_jours_restants
            value: 30
        - logger.log: "Compteur de filtre réinitialisé à 30 jours."

  - platform: restart
    name: "Redémarrer la fontaine"
    id: restart_board

interval:
  - interval: 24h
    then:
      - lambda: |-
          // Récupère la valeur actuelle et retire 1, sans descendre en dessous de 0
          int current = id(filtre_jours_restants).state;
          if (current > 0) {
            id(filtre_jours_restants).publish_state(current - 1);
          }
          
  - interval: 1s
    then:
      - lambda: |-
          if (id(temps_restant_pompe) > 0) id(temps_restant_pompe) -= 1;
          if (id(temps_restant_uv) > 0) id(temps_restant_uv) -= 1;
          
switch:
  - platform: gpio
    pin: P9
    name: "Pompe Fontaine"
    id: pompe
    icon: "mdi:water-pump"

  - platform: gpio
    pin:
      number: P7
      inverted: true
    id: led_statut
    name: "LED Statut"
    icon: "mdi:led-off"

  - platform: gpio
    pin: P17
    name: "Interrupteur Lampe UV"
    id: lampe_uv
    icon: "mdi:lightbulb-fluorescent-tube"
    on_turn_on:
      - if:
          condition:
            lambda: 'return id(mode_uv).current_option() == "Manuel";'
          then:
            - script.execute: minuteur_manuel_uv
    on_turn_off:
      - if:
          condition:
            lambda: 'return id(mode_uv).current_option() == "Manuel";'
          then:
            - script.stop: minuteur_manuel_uv
    
script:
  - id: cycle_uv
    mode: restart
    then:
      - logger.log: "Démarrage du cycle UV : 1 heure actif"
      - switch.turn_on: lampe_uv
      - delay: 1h
      - logger.log: "Pause UV : 7 heures de repos"
      - switch.turn_off: lampe_uv
      - delay: 7h
      - script.execute: cycle_uv
  
  - id: gestion_cycle_pompe
    mode: restart
    then:
      - lambda: |-
          std::string mode = id(mode_pompe).current_option();
          
          if (mode == "Arrêt") {
            id(pompe).turn_off();
          } else {
            id(pompe).turn_on();
          }
      
      - while:
          condition:
            lambda: 'return id(mode_pompe).current_option() == "Intermittent (5m ON / 15m OFF)";'
          then:
            - globals.set: { id: temps_restant_pompe, value: '300' }
            - switch.turn_on: pompe
            - delay: 5min
            - globals.set: { id: temps_restant_pompe, value: '900' }
            - switch.turn_off: pompe
            - delay: 15min

  - id: cycle_uv_auto
    mode: restart
    then:
      - while:
          condition:
            lambda: 'return id(mode_uv).current_option() == "Automatique";'
          then:
            - globals.set: { id: temps_restant_uv, value: '3600' }
            - switch.turn_on: lampe_uv
            - delay: 1h
            - globals.set: { id: temps_restant_uv, value: '25200' }
            - switch.turn_off: lampe_uv
            - delay: 7h

  - id: minuteur_manuel_uv
    mode: restart
    then:
      - globals.set: { id: temps_restant_uv, value: '3600' }
      - delay: 1h
      - switch.turn_off: lampe_uv
      - globals.set: { id: temps_restant_uv, value: '0' }

sensor:
  - platform: template
    name: "Temps restant Pompe"
    id: sensor_temps_pompe
    unit_of_measurement: "s"
    device_class: duration
    update_interval: 10s
    icon: "mdi:timer-sand"
    lambda: |-
      if (id(mode_pompe).current_option() == "Intermittent (5m ON / 15m OFF)") {
        return id(temps_restant_pompe);
      }
      return 0;

  - platform: template
    name: "Temps restant UV"
    id: sensor_temps_uv
    unit_of_measurement: "s"
    device_class: duration
    update_interval: 10s
    icon: "mdi:timer-sand"
    lambda: |-
      if (id(mode_uv).current_option() == "Automatique" || id(lampe_uv).state) {
        return id(temps_restant_uv);
      }
      return 0;
              
binary_sensor:
  - platform: gpio
    pin:
      number: P15
      mode: INPUT_PULLUP
      inverted: true
    name: "Capteur Niveau d'Eau"
    id: capteur_eau
    device_class: problem

  - platform: gpio
    pin:
      number: P8
      mode: INPUT_PULLUP
      inverted: true
    name: "Bouton Physique"
    id: bouton_physique
    on_click:
      - min_length: 50ms
        max_length: 2s
        then:
          - button.press: reset_filtre_btn
          - logger.log: "Bouton (Appui court) : Reset du filtre effectué !"
      
      - min_length: 5s
        max_length: 60s
        then:
          - logger.log: "Bouton (Appui long) : Redémarrage matériel en cours..."
          - button.press: restart_board

  - platform: template
    name: "Statut Lampe UV"
    id: statut_lampe_uv
    lambda: 'return id(lampe_uv).state;'
    icon: "mdi:lightbulb-on-outline"
    
  - platform: status
    name: "Statut Connexion Fontaine"
